### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by FeMIMaKAY** [zuri-training/PROJ-31-debpay#41]

**Comment by okiemuteubogu** [comment]
I worked on the logo design for DEBPAY using design softwares like Photoshop and Illustrator

**Comment by FeMIMaKAY** [comment]
okay i will assign it to you

**Comment by FeMIMaKAY** [comment]
can u submit the page u did here

**Comment by okiemuteubogu** [comment]
> can u submit the page u did here

How do I do that please ? Am I to send like a jpeg ?

**Comment by FeMIMaKAY** [comment]
the link i mean

**Comment by okiemuteubogu** [comment]
![image](https://user-images.githubusercontent.com/105220667/183241081-67feb96e-cfbf-4dd4-9286-20ec63a8128f.png)

**Comment by okiemuteubogu** [comment]
https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=414%3A695

**Comment by Ucheswill** [comment]
Finally I’m in

**Comment by Ucheswill** [comment]
I later confirmed the logo color hex to be #007EA7. Its looking better now.
