### ISSUE TITLE
View Debt Segment for unauthorized users mobile and desktop view

### ISSUE THREAD

**Issue by FeMIMaKAY** [zuri-training/PROJ-31-debpay#45]

**Comment by lorddammy** [comment]
I worked on the mobile and desktop view for this

**Comment by lorddammy** [comment]
It has been completed

**Comment by lorddammy** [comment]
https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=656%3A898
This is the figma link for it
