### ISSUE TITLE
Login Design

### ISSUE THREAD

**Issue by FeMIMaKAY** [zuri-training/PROJ-31-debpay#48]

**Comment by cakebrown** [comment]
I worked on the mobile and desktop view for this

**Comment by lorddammy** [comment]
Can you drop the figma link alongside it

**Comment by lorddammy** [comment]
@cakebrown

**Comment by cakebrown** [comment]
Okay

**Comment by cakebrown** [comment]
I also designed the Sign up page

**Comment by cakebrown** [comment]
https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=824%3A1270

**Comment by cakebrown** [comment]
![image](https://user-images.githubusercontent.com/105297975/183255126-5c576967-4d45-44aa-a948-903687c229b9.png)

**Comment by cakebrown** [comment]
![image](https://user-images.githubusercontent.com/105297975/183255224-c3061bce-0c82-47ad-9e53-295ac31322a4.png)

**Comment by cakebrown** [comment]
![image](https://user-images.githubusercontent.com/105297975/183259274-e1f8e6c6-9f60-49cb-9621-b341781135eb.png)

**Comment by cakebrown** [comment]
![image](https://user-images.githubusercontent.com/105297975/183259302-e6ac30b4-52d0-442d-933c-01c9def0639b.png)

**Comment by cakebrown** [comment]
I am through with designing these pages.

**Comment by cakebrown** [comment]
https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=2583%3A8966

**Comment by cakebrown** [comment]
https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=2583%3A9003

**Comment by cakebrown** [comment]
https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=2583%3A9041

**Comment by cakebrown** [comment]
https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=2583%3A9085

**Comment by cakebrown** [comment]
https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=2583%3A9120

**Comment by cakebrown** [comment]
https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=2583%3A9161

**Comment by cakebrown** [comment]
https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=2587%3A9817

**Comment by cakebrown** [comment]
https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=2587%3A9870

**Comment by cakebrown** [comment]
https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=2587%3A9974

**Comment by cakebrown** [comment]
https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=2587%3A10025

**Comment by cakebrown** [comment]
https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=2993%3A9226

**Comment by cakebrown** [comment]
https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=3001%3A9895

**Comment by cakebrown** [comment]
https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=2993%3A9415

**Comment by cakebrown** [comment]
https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=3001%3A9979

**Comment by cakebrown** [comment]
https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=2993%3A9553

**Comment by cakebrown** [comment]
https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=3005%3A10060

**Comment by cakebrown** [comment]
https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=2587%3A9870

**Comment by cakebrown** [comment]
https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=2587%3A9929

**Comment by cakebrown** [comment]
https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=2587%3A9974

**Comment by cakebrown** [comment]
https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=2587%3A10025

**Comment by cakebrown** [comment]
![image](https://user-images.githubusercontent.com/105297975/184625531-84cb5b72-99a9-4050-b05a-c04e26c8878e.png)

**Comment by cakebrown** [comment]
![image](https://user-images.githubusercontent.com/105297975/184625574-3408e491-42c9-44f0-a78f-73b61679e236.png)

**Comment by cakebrown** [comment]
![image](https://user-images.githubusercontent.com/105297975/184625634-838788d7-d44f-4354-9fe1-0a5d20eb4467.png)

**Comment by cakebrown** [comment]
![image](https://user-images.githubusercontent.com/105297975/184625762-ed002b9e-a934-4bde-a395-694bc0514812.png)

**Comment by cakebrown** [comment]
![image](https://user-images.githubusercontent.com/105297975/184625845-5703d615-aa47-4127-b1e5-790820576b5f.png)

**Comment by cakebrown** [comment]
![image](https://user-images.githubusercontent.com/105297975/184625946-1ad4f169-6520-457c-8394-4d90810de179.png)
