### ISSUE TITLE
Forgot password page design

### ISSUE THREAD

**Issue by FeMIMaKAY** [zuri-training/PROJ-31-debpay#53]

**Comment by lorddammy** [comment]
@cakebrown

**Comment by cakebrown** [comment]
I worked on the mobile and desktop views for this.

**Comment by cakebrown** [comment]
![image](https://user-images.githubusercontent.com/105297975/183256048-3aae5e0a-d1c5-4e25-b7a7-49e395e12da6.png)

**Comment by cakebrown** [comment]
https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=1828%3A4858

**Comment by cakebrown** [comment]
https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=2026%3A5476

**Comment by cakebrown** [comment]
https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=2047%3A5687

**Comment by cakebrown** [comment]
https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=2026%3A5540

**Comment by cakebrown** [comment]
https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=2026%3A5655

**Comment by cakebrown** [comment]
https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=2026%3A5814

**Comment by cakebrown** [comment]
![image](https://user-images.githubusercontent.com/105297975/183257608-2bdcbddc-11b2-4cc1-86a2-718758d4ad96.png)

**Comment by cakebrown** [comment]
![image](https://user-images.githubusercontent.com/105297975/183257740-9fe5bd31-d4e9-4e8e-afd9-b21216924477.png)

**Comment by cakebrown** [comment]
![image](https://user-images.githubusercontent.com/105297975/183257772-74eaecd4-ebe3-4507-b666-6f13d176963d.png)

**Comment by cakebrown** [comment]
![image](https://user-images.githubusercontent.com/105297975/183257835-57e1e0e3-43ac-41c0-b04e-e8cabb1ca74a.png)

**Comment by cakebrown** [comment]
![image](https://user-images.githubusercontent.com/105297975/183257867-64542d22-750a-4a85-b10d-747481fa4033.png)

**Comment by cakebrown** [comment]
![image](https://user-images.githubusercontent.com/105297975/183257912-97bb42f1-babe-4174-bb3e-ee255f1e3857.png)

**Comment by lorddammy** [comment]
@FeMIMaKAY Please assign @cakebrown to this too
