### ISSUE TITLE
Error 404 page design

### ISSUE THREAD

**Issue by FeMIMaKAY** [zuri-training/PROJ-31-debpay#54]

**Comment by lorddammy** [comment]
@Tommy-pro

**Comment by Tommy-pro** [comment]
I designed this page

**Comment by lorddammy** [comment]
You're done with both mobile and desktop right?

**Comment by Tommy-pro** [comment]
Sure😉

**Comment by Tommy-pro** [comment]
https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=1821%3A4309

**Comment by Tommy-pro** [comment]
> https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=1821%3A4309

link to the design

**Comment by Tommy-pro** [comment]
![error 407](https://user-images.githubusercontent.com/105234679/183253485-203a22bc-ce1c-40e5-89b7-ff63d5945582.png)
