### ISSUE TITLE
Settings design page

### ISSUE THREAD

**Issue by FeMIMaKAY** [zuri-training/PROJ-31-debpay#56]

**Comment by lorddammy** [comment]
@marvellousafaola

**Comment by marvellousafaola** [comment]
i just finished working on this

**Comment by marvellousafaola** [comment]
[https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=1878%3A5235](url)

**Comment by marvellousafaola** [comment]
![settings](https://user-images.githubusercontent.com/72315768/183254489-ba351ac3-b071-4510-8e0e-8c64a6802a91.png)
