### ISSUE TITLE
Content development design

### ISSUE THREAD

**Issue by FeMIMaKAY** [zuri-training/PROJ-31-debpay#59]

**Comment by Emmanuellaoboh** [comment]
I curated the content for the dashboard and posts by schools

**Comment by Emmanuellaoboh** [comment]
I put together the terms and conditions and privacy policies

**Comment by Bu-Bee** [comment]
I created the content for the FAQs page.

**Comment by lorddammy** [comment]
@Evytrell

**Comment by Evytrell** [comment]
I created the content for the ‘About Us’ page and Landing Page
