### ISSUE TITLE
Frequently asked question (FAQ)

### ISSUE THREAD

**Issue by gphics** [zuri-training/PROJ-31-debpay#87]

**Comment by Bu-Bee** [comment]
I designed the FAQ page in three states on mobile and desktop screens.

https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=1296%3A3189

https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=1296%3A3245

https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=1865%3A4983

https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=1296%3A2915

https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=1296%3A2854

https://www.figma.com/file/ZDHTMAdJWEHaDPlwLmzv3b/Pro-Team-31-Figma?node-id=1296%3A2972
![FAQ Designs](https://user-images.githubusercontent.com/105268609/183981934-a3da2cfa-9139-4510-87c2-e75f9e58c40f.jpg)

![FAQ Designs](https://user-images.githubusercontent.com/105268609/183982329-b0b260f8-6378-4f81-afb4-0655e9542825.jpg)
